#!/bin/bash
#
#$ -S /bin/bash
 
export MYAPP='echo "hello world"'
export MYAPP_FLAGS=''
 
#$ -N TEST 
#$ -pe openmpi 1
 
. /etc/profile.d/modules.sh

module add gcc
# Load one of these
module add openmpi/gcc
# module add openmpi/psc
# module add openmpi/pgi
# module add openmpi/intel 
  
#$ -cwd
# $ -v MPI_HOME

#PBS -q all 
# Does not require the -machinefile flag
cd /home/slha/WRFV3/run
CMD="$MPI_HOME/bin/mpirun -np $NSLOTS $MYAPP $MYAPP_FLAGS"
 
echo $CMD
 
$CMD

