  tempo(i,:)= (Namelist{1,5}.Analog.weights_state_vector_idx(i)/var_std)*sqrt(((forecast_vector.var_data{2,i}-data_set.data(idx,i)).^2)+...
              ((forecast_vector.var_data{4,i}-data_set.data(idx_t_minus_one,i)).^2)+...
              ((forecast_vector.var_data{6,i}-data_set.data(idx_t_plus_one,i)).^2));