#!/bin/bash

#
# Active comments for SGE 
#
#$ -S /bin/bash
#$ -N WRF
#$ -v MPI_HOME
#$ -cwd
#$ -q all.q
#$ -pe openmpi 8


. /etc/profile.d/modules.sh

# Module stuff
module add gcc
# Load one of these
module add openmpi/gcc
# module add openmpi/psc
# module add openmpi/pgi
# module add openmpi/intel 
  


# Does not require the -machinefile flag

CMD="$MPI_HOME/bin/mpirun -np $NSLOTS /home/slha/forecasting/development/run/wrf.exe"
 
echo $CMD
 
$CMD

