#!/bin/bash

#
# Active comments for SGE 
#
#$ -S /bin/bash
#$ -N <jobname>
#$ -v LD_LIBRARY_PATH
#$ -v PATH
#$ -cwd
#$ -q <qname>
#$ -pe openmpi <nprocs>
#$ -j yes
#$ -o <logfile>

. /etc/profile.d/modules.sh

# Module stuff
module add gcc
module add ncl
module add netcdf/gcc/64/4.3.0
module add hdf5
module add nco
module add udunits
module add gdal
module add vapor
module add imagemagick

# Load one of these
# module add openmpi/gcc
# module add openmpi/psc
# module add openmpi/pgi
# module add openmpi/intel 
  


# Does not require the -machinefile flag

CMD='<executable>'
 
echo $CMD
 
$CMD

